language: julia
os:
  - linux
julia:
  - 1.3
  - 1.2
  - 1
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); if VERSION >= v"1.1" Pkg.build(; verbose = true) else Pkg.build() end; Pkg.test(coverage=true)'
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'using Pkg; import SphericalHarmonicModes; cd(joinpath(dirname(pathof(SphericalHarmonicModes)),"..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
